version: '3.8'

networks:
  bridge:
  proxynet:
    external: true

services:
  nginx:
    container_name: pmnginx
    hostname: pmnginx
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - bridge
      - proxynet
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "/home/georg/data/pmnginx/data:/data"
      - "/home/georg/data/pmnginx/cert:/etc/letsencrypt"
    environment:
      TZ: Europe/Berlin
