version: "3"

networks:
  bridge:
  proxynet:
    external: true

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      bridge:
        aliases:
          - "pihole"
      proxynet:
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "2000:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORDx: '12'
      IPv6: 'false'
      DBINTERVAL: '0'
      FTLPORT: '2000'
    volumes:
      - "/home/docker/data/etc-pihole:/etc/pihole"
      - "/home/docker/data/etc-dnsmasq.d:/etc/dnsmasq.d"
    restart: unless-stopped
