version: '3'
networks:
  bridge:
  proxynet:
    external: true
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant::2024.2
    networks:
      bridge:
      proxynet:
    ports:
      - '8123:8123'
    volumes:
      - /home/georg/data/homeassistant/data:/config
      #- /run/dbus:/run/dbus:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/Berlin
